language: python
services:
  - docker
before_install:
  - docker build -t imparaai/prediction -f cpu.Dockerfile .
script:
  - docker run imparaai/prediction bash -c "pytest"
notifications:
  email:
    on_success: never