language: python
services:
  - docker
before_install:
  - docker build -t imparaai/prediction -f cpu.Dockerfile .
  - docker run imparaai/prediction bash -c "pytest"
script:
  - pytest
notifications:
  email:
    on_success: never